___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [4]:
import numpy as np

### Create an array of 10 zeros 

In [3]:
ar=np.zeros(10)
ar

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
ar=np.ones(10)
ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [16]:
ar=np.ones(10)*5
ar

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [13]:
ar=np.arange(10,51)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [15]:
ar=np.arange(10,51,2)
ar

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [25]:
ar=np.identity(3)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [47]:
ar=np.random.rand(1)
ar

array([0.8477809])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [45]:
np.random.standard_normal(25)

array([-0.58612402, -1.53449476, -1.25272217,  0.88999473,  1.21307804,
       -1.05241463, -0.39607663, -0.12765876,  1.47486737, -0.30552589,
       -0.60202443, -0.443937  ,  0.65874566, -1.88838547,  1.10762129,
        2.79198441,  1.15075624,  0.05659728,  2.39352254, -0.24033315,
        0.2781231 ,  0.26933027,  0.21226661,  0.87854849,  0.58905472])

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [48]:
ar=np.linspace(0,1,20)
ar

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [5]:
mat2 = np.arange(1,26).reshape(5,5)
mat2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [7]:
mat2[2]


array([11, 12, 13, 14, 15])

In [ ]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [24]:
mat2[3:4]

array([[16, 17, 18, 19, 20]])

In [36]:
mat2[2:,1:]


array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [37]:
mat2[0:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [40]:
mat2[3,4]



array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [9]:
mat2[4:]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [10]:
mat2[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])